In [1]:
s = "Hi there Sam!"
s = s.split()
print(s)

['Hi', 'there', 'Sam!']


In [2]:
planet = "Earth"
diameter = 12742
print(f"The diameter of Earth is {diameter} kilometers")

The diameter of Earth is 12742 kilometers


In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [4]:
import numpy as np

In [5]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
array=np.ones(10)*5
print(array)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [7]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


In [8]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [10]:
import pandas as pd

In [11]:
import pandas as pd
a=pd.DataFrame({"row1":[1,2],'row2':[3,4],"row3":[5,6]})
a

row1  row2  row3
0     1     3     5
1     2     4     6

In [12]:
import datetime
test_date = datetime.datetime.strptime('01-1-2023',"%d-%m-%Y")
x=41
date = pd.date_range(test_date,periods = x)
print(date.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


In [13]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [14]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24